# Generated by Django 4.1.5 on 2023-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawticiario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagenes'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagenes'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagenes'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagenes'),
        ),
    ]
