# Generated by Django 4.1.5 on 2023-01-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(upload_to='instagram/post_images'),
        ),
    ]
